/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooMyDecay_full.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooMyDecay_full) 

   RooMyDecay_full::RooMyDecay_full(const char *name, const char *title, 
         RooAbsReal& _t,
         RooAbsReal& _X0,
         RooAbsReal& _pn,
         RooAbsReal& _p2n,
         RooAbsReal& _t1,
         RooAbsReal& _pn2,
         RooAbsReal& _t2,
         RooAbsReal& _pn3,
         RooAbsReal& _t3,
         RooAbsReal& _t4,
         RooAbsReal& _pn5,
         RooAbsReal& _t5,
         RooAbsReal& _pn6,
         RooAbsReal& _t6,
         RooAbsReal& _t7,
         RooAbsReal& _pn8,
         RooAbsReal& _t8,
         RooAbsReal& _t9,
         RooAbsReal& _t10,
         RooAbsReal& _bg) :
      RooAbsPdf(name,title), 
      t("t","t",this,_t),
      X0("X0","X0",this,_X0),
      pn("pn","pn",this,_pn),
      p2n("p2n","p2n",this,_p2n),
      t1("t1","t1",this,_t1),
      pn2("pn2","pn2",this,_pn2),
      t2("t2","t2",this,_t2),
      pn3("pn3","pn3",this,_pn3),
      t3("t3","t3",this,_t3),
      t4("t4","t4",this,_t4),
      pn5("pn5","pn5",this,_pn5),
      t5("t5","t5",this,_t5),
      pn6("pn6","pn6",this,_pn6),
      t6("t6","t6",this,_t6),
      t7("t7","t7",this,_t7),
      pn8("pn8","pn8",this,_pn8),
      t8("t8","t8",this,_t8),
      t9("t9","t9",this,_t9),
      t10("t10","t10",this,_t10),
      bg("bg","bg",this,_bg)
{
}


RooMyDecay_full::RooMyDecay_full(const RooMyDecay_full& other, const char* name) :  
   RooAbsPdf(other,name), 
   t("t",this,other.t),
   X0("X0",this,other.X0),
   pn("pn",this,other.pn),
   p2n("p2n",this,other.p2n),
   t1("t1",this,other.t1),
   pn2("pnd",this,other.pn2),
   t2("t2",this,other.t2),
   pn3("pnd",this,other.pn3),
   t3("t3",this,other.t3),
   t4("t4",this,other.t4),
   pn5("pn5",this,other.pn5),
   t5("t5",this,other.t5),
   pn6("pn6",this,other.pn6),
   t6("t6",this,other.t6),
   t7("t7",this,other.t7),
   pn8("pn8",this,other.pn8),
   t8("t8",this,other.t8),
   t9("t9",this,other.t9),
   t10("t10",this,other.t10),
   bg("bg",this,other.bg)
{
}

Double_t RooMyDecay_full::decay_background() const
{
   return bg;
}

Double_t RooMyDecay_full::decay_parent() const
{
   Double_t result;
   Double_t l1;
   result = 0;
   if(t1>0){
      l1=log(2)/t1;
      Double_t temp;
      temp = TMath::Exp(-1*l1*t);
      result = result + temp;
   }
   return result*X0;
}

Double_t RooMyDecay_full::decay_daughter() const
{
   Double_t result;
   Double_t l1, l2;
   Double_t pb=1-pn-p2n;
   result = 0;
   if(t1>0 && t2>0 && t1!=t2){
      l1=log(2)/t1;
      l2=log(2)/t2;
      Double_t temp;
      temp = l2*(TMath::Exp(-1*l1*t)/(l2-l1)+TMath::Exp(-1*l2*t)/(l1-l2));
      result = result + temp;
   }
   return X0*pb*result;
}

Double_t RooMyDecay_full::decay_gdaughter() const
{
   Double_t result;
   Double_t l1, l2, l3;
   Double_t pb=1-pn-p2n;
   Double_t pb2=1-pn2;
   result = 0;
   if(t1>0 && t2>0 && t3>0 && t1!=t2 && t1!=t3 && t2!=t3){
      l1=log(2)/t1;
      l2=log(2)/t2;
      l3=log(2)/t3;
      Double_t temp;
      temp = l2*l3*(TMath::Exp(-1*l1*t)/(l2-l1)/(l3-l1)+TMath::Exp(-1*l2*t)/(l1-l2)/(l3-l2)+TMath::Exp(-1*l3*t)/(l1-l3)/(l2-l3));
      result = result + temp;
   }
   return X0*pb*pb2*result;
}

Double_t RooMyDecay_full::decay_ggdaughter() const
{
   Double_t result;
   Double_t l1, l2, l3, l4;
   Double_t pb=1-pn-p2n;
   Double_t pb2=1-pn2;
   Double_t pb3=1-pn3;
   result = 0;
   if(t1>0 && t2>0 && t3>0 && t4>0 && t1!=t2 && t1!=t3 && t1!=t4 && t2!=t3 && t2!=t4 && t3!=t4){
      l1=log(2)/t1;
      l2=log(2)/t2;
      l3=log(2)/t3;
      l4=log(2)/t4;
      Double_t temp;
      temp = l2*l3*l4*(TMath::Exp(-1*l1*t)/(l2-l1)/(l3-l1)/(l4-l1)+TMath::Exp(-1*l2*t)/(l1-l2)/(l3-l2)/(l4-l2)+TMath::Exp(-1*l3*t)/(l1-l3)/(l2-l3)/(l4-l3)+TMath::Exp(-1*l4*t)/(l1-l4)/(l2-l4)/(l3-l4));
      result = result + temp;
   }
   return X0*pb*pb2*pb3*result;
}

Double_t RooMyDecay_full::decay_bndaughter() const
{
   Double_t result;
   Double_t l1, l2;
   result = 0;
   if(t1>0 && t5>0 && t1!=t5){
      l1=log(2)/t1;
      l2=log(2)/t5;
      Double_t temp;
      temp = l2*(TMath::Exp(-1*l1*t)/(l2-l1)+TMath::Exp(-1*l2*t)/(l1-l2));
      result = result + temp;
   }
   //cout<<X0*pn*result<<endl;
   return X0*pn*result;
}

Double_t RooMyDecay_full::decay_bngdaughter() const
{
   Double_t result;
   Double_t l1, l2, l3;
   Double_t pb=1-pn-p2n;
   Double_t pb5=1-pn5;
   result = 0;
   if(t1>0 && t5>0 && t6>0 && t1!=t5 && t1!=t6 && t5!=t6){
      l1=log(2)/t1;
      l2=log(2)/t5;
      l3=log(2)/t6;
      Double_t temp;
      temp = l2*l3*(TMath::Exp(-1*l1*t)/(l2-l1)/(l3-l1)+TMath::Exp(-1*l2*t)/(l1-l2)/(l3-l2)+TMath::Exp(-1*l3*t)/(l1-l3)/(l2-l3));
      result = result + pn*pb5*temp;
   }
   if(t1>0 && t2>0 && t6>0 && t1!=t2 && t1!=t6 && t2!=t6){
      l1=log(2)/t1;
      l2=log(2)/t2;
      l3=log(2)/t6;
      Double_t temp;
      temp = l2*l3*(TMath::Exp(-1*l1*t)/(l2-l1)/(l3-l1)+TMath::Exp(-1*l2*t)/(l1-l2)/(l3-l2)+TMath::Exp(-1*l3*t)/(l1-l3)/(l2-l3));
      result = result + pb*pn2*temp;
   }
   return X0*result;
}

Double_t RooMyDecay_full::decay_bnggdaughter() const
{
   Double_t result;
   Double_t l1, l2, l3, l4;
   Double_t pb=1-pn-p2n;
   Double_t pb2=1-pn2;
   Double_t pb5=1-pn5;
   Double_t pb6=1-pn6;
   result = 0;
   if(t1>0 && t2>0 && t3>0 && t7>0 && t1!=t2 && t1!=t3 && t1!=t7 && t2!=t3 && t2!=t7 && t3!=t7){
      l1=log(2)/t1;
      l2=log(2)/t2;
      l3=log(2)/t3;
      l4=log(2)/t7;
      Double_t temp;
      temp = l2*l3*l4*(TMath::Exp(-1*l1*t)/(l2-l1)/(l3-l1)/(l4-l1)+TMath::Exp(-1*l2*t)/(l1-l2)/(l3-l2)/(l4-l2)+TMath::Exp(-1*l3*t)/(l1-l3)/(l2-l3)/(l4-l3)+TMath::Exp(-1*l4*t)/(l1-l4)/(l2-l4)/(l3-l4));
      result = result + pb*pb2*pn3*temp;
   }
   if(t1>0 && t2>0 && t6>0 && t7>0 && t1!=t2 && t1!=t6 && t1!=t7 && t2!=t6 && t2!=t7 && t6!=t7){
      l1=log(2)/t1;
      l2=log(2)/t2;
      l3=log(2)/t6;
      l4=log(2)/t7;
      Double_t temp;
      temp = l2*l3*l4*(TMath::Exp(-1*l1*t)/(l2-l1)/(l3-l1)/(l4-l1)+TMath::Exp(-1*l2*t)/(l1-l2)/(l3-l2)/(l4-l2)+TMath::Exp(-1*l3*t)/(l1-l3)/(l2-l3)/(l4-l3)+TMath::Exp(-1*l4*t)/(l1-l4)/(l2-l4)/(l3-l4));
      result = result + pb*pn2*pb6*temp;
   }
   if(t1>0 && t5>0 && t6>0 && t7>0 && t1!=t5 && t1!=t6 && t1!=t7 && t5!=t6 && t5!=t7 && t6!=t7){
      l1=log(2)/t1;
      l2=log(2)/t5;
      l3=log(2)/t6;
      l4=log(2)/t7;
      Double_t temp;
      temp = l2*l3*l4*(TMath::Exp(-1*l1*t)/(l2-l1)/(l3-l1)/(l4-l1)+TMath::Exp(-1*l2*t)/(l1-l2)/(l3-l2)/(l4-l2)+TMath::Exp(-1*l3*t)/(l1-l3)/(l2-l3)/(l4-l3)+TMath::Exp(-1*l4*t)/(l1-l4)/(l2-l4)/(l3-l4));
      result = result + pn*pb5*pb6*temp;
   }
   return X0*result;
}

Double_t RooMyDecay_full::decay_b2ndaughter() const
{
   Double_t result;
   Double_t l1, l2;
   result = 0;
   if(t1>0 && t8>0 && t1!=t8){
      l1=log(2)/t1;
      l2=log(2)/t8;
      Double_t temp;
      temp = l2*(TMath::Exp(-1*l1*t)/(l2-l1)+TMath::Exp(-1*l2*t)/(l1-l2));
      result = result + temp;
   }
   return X0*p2n*result;
}

Double_t RooMyDecay_full::decay_b2ngdaughter() const
{
   Double_t result;
   Double_t l1, l2, l3;
   Double_t pb8=1-pn8;
   result = 0;
   if(t1>0 && t5>0 && t9>0 && t1!=t5 && t1!=t9 && t5!=t9){
      l1=log(2)/t1;
      l2=log(2)/t5;
      l3=log(2)/t9;
      Double_t temp;
      temp = l2*l3*(TMath::Exp(-1*l1*t)/(l2-l1)/(l3-l1)+TMath::Exp(-1*l2*t)/(l1-l2)/(l3-l2)+TMath::Exp(-1*l3*t)/(l1-l3)/(l2-l3));
      result = result + pn*pn5*temp;
   }
   if(t1>0 && t8>0 && t9>0 && t1!=t8 && t1!=t9 && t8!=t9){
      l1=log(2)/t1;
      l2=log(2)/t8;
      l3=log(2)/t9;
      Double_t temp;
      temp = l2*l3*(TMath::Exp(-1*l1*t)/(l2-l1)/(l3-l1)+TMath::Exp(-1*l2*t)/(l1-l2)/(l3-l2)+TMath::Exp(-1*l3*t)/(l1-l3)/(l2-l3));
      result = result + p2n*pb8*temp;
   }
   return X0*result;
}

Double_t RooMyDecay_full::decay_b3ngdaughter() const
{
   Double_t result;
   Double_t l1, l2, l3;
   result = 0;
   if(t1>0 && t8>0 && t10>0 && t1!=t8 && t1!=t10 && t8!=t10){
      l1=log(2)/t1;
      l2=log(2)/t8;
      l3=log(2)/t10;
      Double_t temp;
      temp = l2*l3*(TMath::Exp(-1*l1*t)/(l2-l1)/(l3-l1)+TMath::Exp(-1*l2*t)/(l1-l2)/(l3-l2)+TMath::Exp(-1*l3*t)/(l1-l3)/(l2-l3));
      result = result + temp;
   }
   return X0*p2n*pn8*result;
}

Double_t RooMyDecay_full::evaluate() const 
{
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   if(pn+p2n<=1 && X0>0 && t1>0){
      return decay_background()+decay_parent()+decay_daughter()+decay_gdaughter()+decay_ggdaughter()+decay_bndaughter()+decay_bngdaughter()+decay_bnggdaughter()+decay_b2ndaughter()+decay_b2ngdaughter()+decay_b3ngdaughter();
   }else{
      return 0;
   }
}
