/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOMYDECAY
#define ROOMYDECAY

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooMyDecay_full : public RooAbsPdf {
public:
  RooMyDecay_full() {} ; 
  RooMyDecay_full(const char *name, const char *title,
	      RooAbsReal& _t,        //decay time (variable in the fitting)
	      RooAbsReal& _X0,       //initial activity 
	      RooAbsReal& _pn,       //Pn of parent
	      RooAbsReal& _p2n,      //P2n of parent
	      RooAbsReal& _t1,      //half-life of the ground state of parent
	      RooAbsReal& _pn2,      //neutron emission of daughter
	      RooAbsReal& _t2,      //half-life of the ground state of daughter
	      RooAbsReal& _pn3,      //neutron emission of grand-daughter
	      RooAbsReal& _t3,      //half-life of the ground state of grand-daughter
	      RooAbsReal& _t4,      //half-life of the ground state of grand-grand-daughter
	      RooAbsReal& _pn5,    //Pn of beta-n daughter
	      RooAbsReal& _t5,      //half-life of the ground state of beta-n daughter
	      RooAbsReal& _pn6,    //Pn of beta-n grand-daughter
	      RooAbsReal& _t6,      //half-life of the ground state of beta-n grand-daughter
	      RooAbsReal& _t7,      //half-life of the ground-state of beta-n grand-grand daughter (set to 0 if not exist)
	      RooAbsReal& _pn8,    //Pn of beta-2n daughter
	      RooAbsReal& _t8,      //half-life of the ground state of beta-2n daughter
	      RooAbsReal& _t9,      //half-life of the ground state of beta-2n grand-daughter
	      RooAbsReal& _t10,      //half-life of the ground state of beta-3n grand-daughter (populated by parent->b2n->bn decay channel)
	      RooAbsReal& _bg);       //constatn background
  RooMyDecay_full(const RooMyDecay_full& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooMyDecay_full(*this,newname); }
  inline virtual ~RooMyDecay_full() { }

protected:

  RooRealProxy t ;
  RooRealProxy X0 ;
  RooRealProxy pn ;
  RooRealProxy p2n ;
  RooRealProxy t1 ;
  RooRealProxy pn2 ;
  RooRealProxy t2 ;
  RooRealProxy pn3 ;
  RooRealProxy t3 ;
  RooRealProxy t4 ;
  RooRealProxy pn5 ;
  RooRealProxy t5 ;
  RooRealProxy pn6 ;
  RooRealProxy t6 ;
  RooRealProxy t7 ;
  RooRealProxy pn8 ;
  RooRealProxy t8 ;
  RooRealProxy t9 ;
  RooRealProxy t10 ;
  RooRealProxy bg ;
  
  Double_t evaluate() const ;
  Double_t decay_background() const ;
  Double_t decay_parent() const ;
  Double_t decay_daughter() const ;
  Double_t decay_gdaughter() const ;
  Double_t decay_ggdaughter() const ;
  Double_t decay_bndaughter() const ;
  Double_t decay_bngdaughter() const ;
  Double_t decay_bnggdaughter() const ;
  Double_t decay_b2ndaughter()const ;
  Double_t decay_b2ngdaughter()const ;
  Double_t decay_b3ngdaughter()const ;

private:

  ClassDef(RooMyDecay_full,1) // Your description goes here...
};
 
#endif
